# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 600  # 10 minutes en secondes
        cookie_lifetime: 600  # 10 minutes en secondes

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
