# config/services.yaml
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    limiter.contact_form_factory:
        class: Symfony\Component\RateLimiter\RateLimiterFactory
        arguments:
            $config: '@rate_limiter.contact_form'

    limiter.contact_form:
        class: Symfony\Component\RateLimiter\Limiter
        factory: ['@limiter.contact_form_factory', 'create']
